name: Publish to PyPI

on:
  release:
    types:
      - published

env:
  PACKAGE_NAME: scryfall

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.6.3"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
            
    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Build and publish packages
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        uv build
        uv publish